### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by R3uan3** [ThePBone/SlidingStackedWidget#3]
Inside of `demo.cpp` theres is `#include "ui_demo.h"`
but you didn't provide this file.

**Comment by timschneeb** [comment]
`ui_demo.h` is automatically generated from `demo.ui` using Qt's UIC and MOC compiler. You need to use Qmake or load the project file inside Qt Creator to setup a suitable development environment for Qt apps.
 Or alternatively invoke the uic and moc compiler manually to generate the header files by hand.
